config/routes.rb
Rails.application.routes.draw do
  resources :ponies
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pony.rb
class Pony < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ponies_controller.rb
class PoniesController < ApplicationController
  before_action :set_pony, only: %i[ show edit update destroy ]

  # GET /ponies or /ponies.json
  def index
    @ponies = Pony.all
  end

  # GET /ponies/1 or /ponies/1.json
  def show
  end

  # GET /ponies/new
  def new
    @pony = Pony.new
  end

  # GET /ponies/1/edit
  def edit
  end

  # POST /ponies or /ponies.json
  def create
    @pony = Pony.new(pony_params)

    respond_to do |format|
      if @pony.save
        format.html { redirect_to pony_url(@pony), notice: "Pony was successfully created." }
        format.json { render :show, status: :created, location: @pony }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pony.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ponies/1 or /ponies/1.json
  def update
    respond_to do |format|
      if @pony.update(pony_params)
        format.html { redirect_to pony_url(@pony), notice: "Pony was successfully updated." }
        format.json { render :show, status: :ok, location: @pony }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pony.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ponies/1 or /ponies/1.json
  def destroy
    @pony.destroy

    respond_to do |format|
      format.html { redirect_to ponies_url, notice: "Pony was successfully destroyed." }
      format.json { head :no_content }
      #newthing
      format.js { render :layout=>false}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pony
      @pony = Pony.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pony_params
      params.require(:pony).permit(:name, :profession)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ponies_helper.rb
module PoniesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ponies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ponies/_form.html.erb
<%= form_with(model: pony) do |form| %>
  <% if pony.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pony.errors.count, "error") %> prohibited this pony from being saved:</h2>

      <ul>
        <% pony.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :profession, style: "display: block" %>
    <%= form.text_field :profession %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ponies/_pony.html.erb
<div id="<%= dom_id pony %>">
  <p>
    <strong>Name:</strong>
    <%= pony.name %>
  </p>

  <p>
    <strong>Profession:</strong>
    <%= pony.profession %>
  </p>

</div>

app/views/ponies/destroy.js.erb
$(".delete_pony").bind("ajax:success", function() {
    $(this).closest("tr").fadeOut();
})

app/views/ponies/edit.html.erb
<h1>Editing pony</h1>

<%= render "form", pony: @pony %>

<br>

<div>
  <%= link_to "Show this pony", @pony %> |
  <%= link_to "Back to ponies", ponies_path %>
</div>

app/views/ponies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ponies</h1>
<%= link_to "New pony", new_pony_path %>
<table id="ponies">
  <thead>
    <tr>
      <th>name:</th>
      <th>profession:</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @ponies.each do |pony| %>
      <tr>
        <td><%= pony.name%></td>
        <td><%= pony.profession %></td>
        <td><%= link_to "Show this pony", pony %> | <%= button_to "Destroy this pony", @pony, method: :delete, data: { confirm: "are you sure?"} :remote=>true, :class=> "delete_pony" %></td>
      <tr>

  <% end %>
</div>

app/views/ponies/new.html.erb
<h1>New pony</h1>

<%= render "form", pony: @pony %>

<br>

<div>
  <%= link_to "Back to ponies", ponies_path %>
</div>

app/views/ponies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pony %>

<div>
  <%= link_to "Edit this pony", edit_pony_path(@pony) %> |
  <%= link_to "Back to ponies", ponies_path %>

  <%= button_to "Destroy this pony", @pony, method: :delete, :remote=>true, :class=> "delete_pony" %>
</div>